global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "httptrafic"
    honor_labels: true
    static_configs:
      - targets: ["apppy:5000"]
  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']
